### PR TITLE
Remove Openlogin & CustomAuth

### PR DESCRIPTION
**Pull request by yashovardhan**
Removed all instances of OpenLogin and CustomAuth from the torus documentation.

### CODE REVIEW

**Comment by yashovardhan** [comment]
Adding this on priority right now, please approve to remove the pages that are adding confusion. I'll add a proper explanation of the stack further in a week or two..

**Comment by himanshuchawla009** [comment]
Web3Auth currently doesn't support custom auth out of the box (getTorusKey, getAggregateTorusKey is not supported)  so I m not very sure that we want to remove it. Although open login can be removed. Also, many people want to use Web3Auth without open login ie. just social login which is not possible yet with Web3Auth.

**Comment by yashovardhan** [comment]
Zhen asked me to remove this over a chat, that's why submitted the PR. I'll be adding an explanation later.

**Comment by YZhenY** [comment]
deprecate, not remove

**Pull request closed without merging**
